# TODO: Code is not currently in use...
config = {
  host: "http://localhost:9200/",
  transport_options: {
    request: { timeout: 250 }
  },
  retry_on_failure: true
}

if File.exists?("config/elasticsearch.yml")
  config.merge!(YAML.load_file("config/elasticsearch.yml").symbolize_keys)
end

Elasticsearch::Model.client = Elasticsearch::Client.new(config)
